# Generated by Django 4.2.2 on 2024-10-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.CharField(max_length=40)),
                ('gst_no', models.CharField(max_length=20)),
                ('dd', models.DateField()),
                ('d_address', models.CharField(max_length=300)),
                ('d_mobile_no', models.IntegerField()),
                ('contact_name', models.CharField(max_length=20)),
            ],
        ),
    ]
