# Generated by Django 4.2.2 on 2024-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_grainorder_groceryorder_medorder_stationaryorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('med_combination', models.CharField(blank=True, max_length=100, null=True)),
                ('med_dealer', models.CharField(max_length=50)),
                ('med_category', models.CharField(max_length=20)),
                ('med_mrp', models.IntegerField()),
                ('med_up', models.IntegerField()),
                ('med_u_gst', models.FloatField()),
                ('med_gst', models.IntegerField()),
                ('med_qty', models.IntegerField()),
                ('med_unit', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_amt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_amt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_b1_d',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_b2_d',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_bill_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_bill_no2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_bill',
            name='med_invoice_d',
            field=models.DateField(blank=True, null=True),
        ),
    ]
