# Generated by Django 4.2.2 on 2024-11-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_all_product_grain_grain_order_grocery_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_dealer', models.CharField(max_length=100)),
                ('pro_type', models.CharField(max_length=30)),
                ('pro_cat', models.CharField(max_length=30)),
                ('pro_mrp', models.IntegerField()),
                ('pro_up', models.IntegerField()),
                ('pro_gst', models.IntegerField()),
                ('pro_gst_price', models.IntegerField()),
                ('pro_qty', models.IntegerField()),
                ('pro_unit', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Medi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('med_combination', models.CharField(blank=True, max_length=100, null=True)),
                ('med_dealer', models.CharField(max_length=50)),
                ('med_category', models.CharField(max_length=20)),
                ('med_mrp', models.IntegerField()),
                ('med_up', models.IntegerField()),
                ('med_u_gst', models.IntegerField()),
                ('med_gst', models.IntegerField()),
                ('med_qty', models.IntegerField()),
                ('med_unit', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Grain',
            new_name='Grains',
        ),
        migrations.DeleteModel(
            name='All_Product',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
